email = "loginrevoked@gmail.com"
password = "dsog mgzx asiz bsjm"
maglink_regex = "https://claude\\.ai/magic-link#\\S+"
imap_host = "imap.gmail.com"
email_password = "dsog mgzx asiz bsjm"
filter_query = 'UNSEEN FROM "anthropic.com"'
vercode_pagemarker = "Use verification code to continue"
vercode_regex = "\\b(\\d{6})\\b"
poll_interval = 60 # seconds
home_page = "index.html"
max_linkcache = 100